### ISSUE TITLE
Tailwind not work on the repo

### ISSUE THREAD

**Issue by kenwCoding** [Telegram-Mini-Apps/nextjs-template#15]
Add following into the `_assets/globals.css` file:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

body {
    background: var(--tg-theme-secondary-bg-color, white);
}
```
